tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    php_mess_detector: true
    php_changetracking: true
    php_code_sniffer: true
    php_cs_fixer: true
    sensiolabs_security_checker: true

filter:
    excluded_paths:
        - 'test/*'
