language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer selfupdate
  - composer install

after_script:
  - vendor/bin/test-reporter

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/802f417bb6e3e1e8b20d
    on_success: always
    on_failure: always
    on_start: false
